project:
  type: website
  # output-dir: docs


website:
  title: "Pedro Rebollo"
  description: "I am a scientist" #la descripcion que aparece cuando googleas
  site-url: https://pakillo.github.io/academic-website-template-Quarto #poner direccion de mi repo
  repo-url: https://github.com/Pakillo/academic-website-template-Quarto #poner direccion de mi repo
  # favicon: logo.png
  twitter-card: true
  #   creator: "@handle"
  #   site: "@handle"
  open-graph: true
  # google-analytics:
  #   tracking-id: "UA-XXXXXXXX"
  #   anonymize-ip: true
  # cookie-consent: true


  navbar: ###para cambiar la barra de navegacion
    left: ##alineacion del texto
      - href: index.qmd
        text: Home ##Esto es para añadir pestañas en la barra de navegacion
      - Projects.qmd
      - Publications.qmd
      - Blog.qmd

      # - icon: mastodon
      #   href: https://joinmastodon.org
      # - text: "{{< iconify fa6-brands bluesky title='BlueSky'>}}"
      #   href: https://bsky.app
      # - text: "{{< iconify fa6-brands x-twitter title='Twitter'>}}"
      #   href: https://x.com
      # - icon: github
      #   href: https://github.com
      # - icon: linkedin
      #   href: https://linkedin.com/
      # - text: "{{< iconify academicons google-scholar-square size=1.2em title='Scholar'>}}"
      #   href: https://scholar.google.com
      # - text: "{{< iconify fa6-brands orcid size=1.2em title='ORCID' >}}"
      #   href: https://orcid.org/
      - icon: rss
        href: index.xml
      # - icon: twitter
      #   href: https://twitter.com

  page-footer:
    background: light
    right: "Made with Quarto"
  # back-to-top-navigation: true


format:
  html:
    theme: flatly
    css: styles.css
    toc: false

execute:
  freeze: auto  # re-render only when source changes



